language: python
branches:
  except:
  - gh-pages
cache:
  directories:
  - "${HOME}/.pip"
before_cache:
- find ${HOME}/.pip -name log -o -name __pycache__ -type d | xargs -I {} rm -rf {}
matrix:
  fast_finish: true
  allow_failures:
  - python: 3.6
install:
- pip install tox
- pip install tox-travis
script:
- tox
after_success:
- pylint steenzout
- pip install coveralls
- coveralls
deploy:
  provider: pypi
  user: steenzout
  password:
    secure: 'execute "travis encrypt ${TRAVIS_PASSWORD} --add deploy.password"'
  on:
    tags: true
notifications:
  email: false
  slack:
    template:
    - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
    - "%{build_url}"
    - "'%{commit_subject}' by %{author}"
    - "%{elapsed_time} : %{duration}"
    - "%{message}"
    rooms:
      secure: cMw16G5yS/zFg74NZnd/e0KeLlYvG2R1ZNM0JsGW7z+9gfCIBEGr/2aDLR/DPw4WejSpeCWVIS+rqmfYGKKRR4irRkCNxGJCYe/Tfmo9/ZNH9rXK0FM18jQyUx8y6pyMGW+u4f4UWf+hQXrbh5ucjOrCAeWIREIWlOVWo0L0/V8=
    on_success: always
    on_failure: always
